### ISSUE TITLE
Different default key bindings

### ISSUE THREAD

**Issue by rloporp** [m4ns0ur/base64-vscode-plugin#4]
Maybe you should consider a different set of key bindings. With the current ones:
```
encode text to Base64:  Ctrl+Shift+6 (Ctrl+Cmd+6 in Mac)
decode Base64 to text:  Ctrl+Shift+7 (Ctrl+Cmd+7 in Mac) <--- Same as Toggle Line Comment
encode Hex to Base64:   Ctrl+Shift+8 (Ctrl+Cmd+8 in Mac)
decode Base64 to Hex:   Ctrl+Shift+9 (Ctrl+Cmd+9 in Mac)
```
The current key binding for `decode Base64 to text` is (outside Mac) identical to the widely used `Toggle Line Comment`, _de facto_ disabling it.

It took me very long to figure it why my line comment shortcut wasn't working, and it turned out that this extension had "broken" it.

**Comment by m4ns0ur** [comment]
Thanks for reporting the issue!
So what key binding(s) do you suggest as a Mac user?

**Comment by rloporp** [comment]
I'm both a Mac/Linux user.
TBH I don't have a strong opinion about any specific keyboard shortcut, feel free to choose whatever you prefer.
Thank you!!

**Comment by m4ns0ur** [comment]
Sure! Most probably I go with the same shortcuts in Linux and Mac (Ctrl+Shift+{6..9}).

**Comment by rloporp** [comment]
Ahhhh, now I got the misunderstanding:
`Ctrl` + `Shift` + `7` (`Ctrl` + `/`) toggles line comments in several [ISO keyboard layouts](https://en.wikipedia.org/wiki/List_of_QWERTY_keyboard_language_variants), including Danish, Italian, Portuguese, Spanish, Swedish, Turkish, etc.

You probably have an ANSI keyboard with the `/` somewhere else.

So, to sum up, in order to suffer the problem, two circumstances must concur:
* Windows or Linux (not Mac)
* Several ISO keyboard layouts

**Comment by rloporp** [comment]
I spent some minutes learning from Wikipedia, and the `/` collision also happens on ANSI Spanish keyboards (several million users there).

**Comment by m4ns0ur** [comment]
Interesting! Yeah I set the shortcuts based on English layout (where ? and / sit near right Shift).
I guess the safer option would be a combination with letters. Maybe Ctrl+Shift+E, Ctrl+Shift+D, Ctrl+Shift+H, Ctrl+Shift+X.

**Comment by rloporp** [comment]
I'm afraid VSCode core keyboard shortcuts are already "crowded":
* `Ctrl` + `Shift` + `E`: View: Show Explorer
* `Ctrl` + `Shift` + `D`: View: Show Run and Debug
* `Ctrl` + `Shift` + `H`: Search: Replace in Files
* `Ctrl` + `Shift` + `X`: View: Show Extensions

Maybe you can leave the shortcuts empty and let the end users choose their own (?).

**Comment by m4ns0ur** [comment]
I assume having a set of default keybindings is a good idea, as it works out of the box for a variety of users (for sure, users can [customize](https://code.visualstudio.com/docs/getstarted/keybindings) it afterward).

I spent some time to check what is the best practice and it seems having a keybindings using chords (for instance Ctrl+k in Linux and Windows - ⌘+k in Mac) is the best option.

What do you think?
```
encode text to Base64:  Ctrl+k Ctrl+4 (⌘+k ⌘+4 in Mac)
decode Base64 to text:  Ctrl+k Ctrl+5 (⌘+k ⌘+5 in Mac)
encode Hex to Base64:   Ctrl+k Ctrl+6 (⌘+k ⌘+6 in Mac)
decode Base64 to Hex:   Ctrl+k Ctrl+7 (⌘+k ⌘+7 in Mac)
```
