### ISSUE TITLE
Wrong decoding of unprintable characters in text editor mode

### ISSUE THREAD

**Issue by rocketrogerdcook** [m4ns0ur/base64-vscode-plugin#6]
I was in text editor mode and copy/pasted in a base64 encoded string that was an encoded JPG file. When decoded then reopened in Hex Editor mode, I was expecting it to start with FF D8 FF, but instead, it started with several instances of EF BF BD, the REPLACEMENT CHARACTER as encoded in UTF-8.

Manual decoding resulted in the expected FF D8 FF at the beginning of the file, so this appears to be a bug in decoding unprintable characters while in text editor mode.

### To reproduce:

1. Copy this text snippet into a text editor window in VS Code with the base64 extension installed (it is a 1x1 JPG file):
```
/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAABAAEDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAABf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAVAQEBAAAAAAAAAAAAAAAAAAAFBv/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AEwiEf/Z
```
2. Select all, and run the Base64 Decode command.
3. Select all, and run the Base64 Encode command.

### Expected result:

1. The encoded text should be equivalent to the text entered earlier.

### Actual result:

1. The encoded text is different from that which was entered. Decoding the newly-encoded text yields a binary result that begins with four instances of the "REPLACEMENT CHARACTER" UTF-8 sequence.

### Other notes:

About Visual Studio Code:
Version: 1.89.0 (Universal)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:10.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0

Extension version: v1.0.0

Also reproducible on Linux x64 6.7.12-amd64.

**Comment by m4ns0ur** [comment]
It looks like a bug in VS Code [hexeditor](https://github.com/microsoft/vscode-hexeditor).
Steps to reproduce without using the base64 extension:
- create a new text file with some text in it 
![Screenshot from 2024-05-10 11-09-41](https://github.com/m4ns0ur/base64-vscode-plugin/assets/1175855/6538dbec-b669-4db5-a20f-f4faa576d2b4)
- open the file in hex editor mode and replace the text with some hex bytes 
![Screenshot from 2024-05-10 11-10-00](https://github.com/m4ns0ur/base64-vscode-plugin/assets/1175855/436347d1-6d49-4464-ad07-20363f55daec)
- save and close the hex editor
- get back to the text file and add a text and save 
![Screenshot from 2024-05-10 11-10-48](https://github.com/m4ns0ur/base64-vscode-plugin/assets/1175855/df711a87-3366-4302-abb9-4ee3cd28354e)
- open the file in hex editor mode again 
![Screenshot from 2024-05-10 11-10-58](https://github.com/m4ns0ur/base64-vscode-plugin/assets/1175855/98627ea2-db02-413b-ad9b-8ea71ce032ec)
- hex bytes are corrupted with EF BF BD ...

Still as a workaround you can use base64 extension in hex mode (hex decode your base64 data, modify it and hex encode again).
In the future, we can add a hex editing mode for base64 extension (with structured hex bytes), as a nice-to-have feature.
